version: "3.7"

# Development environment override
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-tickets
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
