version: "3.7"

# Development environment override
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-events
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
